// To run these sample requests, install
// the "humao.rest-client" plugin for Visual Studio Code

// Twitter API reference:
// https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

GET https://api.twitter.com/1.1/search/tweets.json?q=tweet&result_type=popular&count=5
Authorization: Bearer {{$dotenv BEARER_TOKEN}}

###

GET https://api.twitter.com/1.1/search/tweets.json?q=anthony&result_type=popular&count=5
Authorization: Bearer {{$dotenv BEARER_TOKEN}}


